In [2]:
# 1.import Numpy package under the name np
import numpy as np

In [5]:
# 2. Pint Numpy version and configuration   
print(np.version)
np.show_config

<module 'numpy.version' from 'C:\\Users\\Tinashe.Kaseke\\python\\lib\\site-packages\\numpy\\version.py'>


<function numpy.__config__.show()>

In [6]:
# 3. Create a null vector of size 10
T=np.zeros(10)
T

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# 4.  Get documentation on add function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
# 5. Create a null vector of size 10 but the fifth value must be 1
U = np.zeros(10)
U[4]=1
print(U)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# 6. Create a vector with values ranging from 10 to 49
V = np.arange(10,50)
V

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
# 7. Reverse the order of a vector
W = np.arange(50)
W = W[::-1]
W

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [18]:
# 8. Create a 3 x 3 matrix with values ranging from 0 to 8
Y = np.arange(0,9).reshape(3,3)
Y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# 9. Find indices of non-zero elements from [1,2,0,0,4,0]
Z = np.nonzero([1,2,0,0,4,0])
Z

(array([0, 1, 4], dtype=int64),)

In [20]:
# 10. Create a 3 x 3 identity matrix
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# 11. Create a 3 x 3 x 3 matrix with random values
B=np.random.random([3,3,3])
B

array([[[0.38103893, 0.31251426, 0.89751711],
        [0.63246923, 0.39029927, 0.87812514],
        [0.01745019, 0.07681018, 0.5482349 ]],

       [[0.8705634 , 0.571296  , 0.68271871],
        [0.45548326, 0.78462496, 0.55384795],
        [0.41331205, 0.91106269, 0.13672964]],

       [[0.13796736, 0.90369962, 0.98349628],
        [0.80087021, 0.78713505, 0.90026625],
        [0.13285078, 0.11866558, 0.99043911]]])

In [26]:
# 12. Create a 10 x 10 array with random values and find minimum and maximum
C=np.random.random([10,10])
Cmin,Cmax=C.min(),C.max()
print(Cmin,Cmax)

0.01371897807495659 0.9954286180811024


In [27]:
# 13. Create a random vector of size 30 and find the mean
D=np.random.random(30)
Davg=D.mean()
print(Davg)

0.46093583061840043
